"""Generate local, synthetic browser-test PDFs; requires pypdf (not a runtime dependency)."""
from pathlib import Path
from base64 import b64encode
from io import BytesIO
from pypdf import PdfWriter
from pypdf.generic import DictionaryObject as D, NameObject as N, ArrayObject as A, NumberObject as I, TextStringObject as T, DecodedStreamObject

writer = PdfWriter()
page = writer.add_blank_page(300, 400)
second_page = writer.add_blank_page(300, 400)
font = writer._add_object(D({N('/Type'): N('/Font'), N('/Subtype'): N('/Type1'), N('/BaseFont'): N('/Helvetica')}))
resources = D({N('/Font'): D({N('/F1'): font})})
fields, annotations = A(), A()

def widget(ft, name, rect, value=None, flags=0, **extra):
    data = D({N('/Type'): N('/Annot'), N('/Subtype'): N('/Widget'), N('/FT'): N(ft), N('/T'): T(name), N('/TU'): T(name), N('/Rect'): A([I(n) for n in rect]), N('/F'): I(4), N('/Ff'): I(flags), N('/DA'): T('/F1 12 Tf 0 g'), N('/P'): page.indirect_reference})
    if value is not None: data[N('/V')] = value
    for key, val in extra.items(): data[N('/'+key)] = val
    ref = writer._add_object(data)
    fields.append(ref)
    annotations.append(ref)
    return data, ref

widget('/Tx', 'Full name', [30, 330, 230, 354], T('Before'))
widget('/Tx', 'Notes', [30, 255, 230, 315], T('Initial notes'), flags=4096)
widget('/Tx', 'Read only', [30, 220, 230, 244], T('Locked'), flags=1)

def appearance(checked):
    stream = DecodedStreamObject()
    stream.set_data(b'0 0 20 20 re S\n' + (b'0 0 m 20 20 l S\n' if checked else b''))
    stream.update({N('/Type'): N('/XObject'), N('/Subtype'): N('/Form'), N('/BBox'): A([I(0),I(0),I(20),I(20)]), N('/Resources'): D()})
    return writer._add_object(stream)

off, on = appearance(False), appearance(True)
widget('/Btn', 'Agree', [30, 180, 50, 200], N('/Off'), AP=D({N('/N'): D({N('/Off'): off,N('/Yes'): on})}), AS=N('/Off'))
widget('/Ch', 'Country', [70, 178, 230, 202], T('IN'), flags=131072, Opt=A([A([T('IN'),T('India')]),A([T('US'),T('United States')])]))
widget('/Ch', 'Topics', [30, 75, 230, 125], A([T('A')]), flags=2097152, Opt=A([T('A'),T('B'),T('C')]))
parent = D({N('/FT'):N('/Btn'),N('/T'):T('Plan'),N('/Ff'):I(32768),N('/V'):N('/First')})
parent_ref = writer._add_object(parent)
kids = A()
for index, name in enumerate(['First','Second']):
    child = D({N('/Type'):N('/Annot'),N('/Subtype'):N('/Widget'),N('/Parent'):parent_ref,N('/Rect'):A([I(30+index*40),I(140),I(50+index*40),I(160)]),N('/F'):I(4),N('/P'):page.indirect_reference,N('/AP'):D({N('/N'):D({N('/Off'):off,N('/'+name):on})}),N('/AS'):N('/First' if index==0 else '/Off')})
    ref=writer._add_object(child)
    kids.append(ref)
    annotations.append(ref)
parent[N('/Kids')]=kids
fields.append(parent_ref)
page[N('/Annots')]=annotations
writer._root_object[N('/AcroForm')]=writer._add_object(D({N('/Fields'):fields,N('/DR'):resources,N('/DA'):T('/F1 12 Tf 0 g')}))
# Supply real page content and appearance streams, as a normal fillable PDF would.
def page_content(target, lines):
    target[N('/Resources')] = resources
    content = DecodedStreamObject()
    commands = ['0.12 0.22 0.35 rg']
    for text, x, y, size in lines:
        commands.append(f'BT /F1 {size} Tf {x} {y} Td ({text}) Tj ET')
    content.set_data(('\n'.join(commands)).encode('ascii'))
    target[N('/Contents')] = writer._add_object(content)

page_content(page, [
    ('Registration form', 30, 375, 18),
    ('Full name', 30, 359, 9), ('Notes', 30, 319, 9),
    ('Read-only reference', 30, 248, 9),
    ('Agree', 30, 207, 9), ('Country', 70, 207, 9),
    ('Plan: Basic / Pro', 30, 165, 9), ('Topics', 30, 129, 9),
    ('Fill in the fields and download to save.', 30, 44, 10),
])
page_content(second_page, [
    ('Document guide', 30, 370, 18),
    ('1. Fill out the registration form.', 30, 335, 12),
    ('2. Choose your country and plan.', 30, 310, 12),
    ('3. Select one or more topics.', 30, 285, 12),
    ('4. Download to keep your changes.', 30, 260, 12),
    ('Navigation', 30, 215, 15),
    ('Use page previews or bookmarks', 30, 190, 12),
    ('to move between these two pages.', 30, 170, 12),
])
writer.update_page_form_field_values(page, {'Full name': 'Before', 'Notes': 'Initial notes', 'Read only': 'Locked', 'Country': 'IN', 'Topics': ['A']}, auto_regenerate=False)

root = writer.add_outline_item('Chapter one',0)
writer.add_outline_item('Details on page two',1,parent=root)

def encode(writer):
    output=BytesIO()
    writer.write(output)
    return b64encode(output.getvalue()).decode('ascii')
plain=encode(writer)
writer.encrypt('viewer-test', owner_password='fixture-owner', algorithm='RC4-128')
encrypted=encode(writer)
Path(__file__).with_name('pdf-fixtures.ts').write_text('''// Synthetic fixtures generated by build-fixtures.py. No external PDFs or CDN required.
const plain = '%s';
const encrypted = '%s';
function bytes(base64: string): Uint8Array { return Uint8Array.from(atob(base64), char => char.charCodeAt(0)); }
export function formPdf(): Uint8Array { return bytes(plain); }
export function passwordPdf(): Uint8Array { return bytes(encrypted); }
''' % (plain,encrypted))
